import Head from 'next/head'

import styles from '../styles/Home.module.css'
import { useState, useEffect } from 'react'

const lastDayOfTheMonth = (date) => {
  return new Date(date.getFullYear(), date.getMonth() + 1, 0).getDate()
}

const MONTHS = [
  'Enero',
  'Febrero',
  'Marzo',
  'Abril',
  'Mayo',
  'Junio',
  'Julio',
  'Agosto',
  'Septiembre',
  'Octubre',
  'Noviembre',
  'Diciembre',
]

const DAYS = ['DOM', 'LUN', 'MAR', 'MIE', 'JUE', 'VIE', 'SAB']

export default function Home() {
  const ACTUAL_DATE = new Date()
  const FIRST_DAY = new Date(
    ACTUAL_DATE.getFullYear(),
    ACTUAL_DATE.getMonth(),
    1
  ).getDay()

  const [data, setData] = useState([])
  const [month] = useState({
    name: MONTHS[ACTUAL_DATE.getMonth()],
    firstDay: FIRST_DAY,
  })
  console.log(month)

  useEffect(() => {
    const lastDay = lastDayOfTheMonth(ACTUAL_DATE)

    setData(
      Array.from({ length: lastDay }, (_, i) => ({
        day: i + 1,
        checked: false,
      }))
    )
    localStorage.getItem('data') &&
      setData(JSON.parse(localStorage.getItem('data')))
  }, [])

  const dayClickEvent = (idx) => {
    const newData = [...data]
    newData[idx].checked = !newData[idx].checked
    setData(newData)
    localStorage.setItem('data', JSON.stringify(newData))
  }

  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Habits | Habits</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>Calendario</h1>
          <section>
            <h3>{month.name}</h3>
            <ol>
              {DAYS.map((day) => (
                <li key={day} className="daysName">
                  {day}
                </li>
              ))}
              {data.map((item, idx) => (
                <li
                  key={item.day}
                  className={item.checked ? 'days checked' : 'days'}
                  onClick={() => dayClickEvent(idx)}
                >
                  <span>{item.day}</span>
                </li>
              ))}
            </ol>
          </section>
        </main>
        <style jsx>{`
          li:nth-child(8) {
            grid-column-start: ${month.firstDay + 1};
          }

          .daysName {
            color: #000;
            cursor: default;
            font-weight: 600;
          }

          span {
            font-weight: 600;
            z-index: 3;
            display: block;
          }

          section {
            display: flex;
            justify-content: center;
            align-items: center;
            flex-direction: column;
          }
          ol {
            display: grid;
            grid-template-columns: repeat(7, 1fr);
            grid-template-rows: repeat(5, 1fr);
            gap: 0.5rem;
            list-style: none;
            padding: 0;
          }

          li {
            background-color: #fff;
            border: 1px solid #eaeaea;
            border-radius: 0.5rem;
            padding: 1rem;
            text-align: center;
            color: #333;
            user-select: none;
            cursor: pointer;
            border: 0;
          }

          /* cross in container */
          .checked {
            background-color: #fe6f61;
            position: relative;
          }

          .checked::before {
            transform: rotate(45deg);
          }

          .checked::after {
            transform: rotate(-45deg);
          }

          .checked::before,
          .checked::after {
            content: '';
            position: absolute;
            top: 0;
            left: 50%;
            width: 1px;
            height: 100%;
            background-color: #eaeaea;
            z-index: 0;
          }
        `}</style>
      </div>
    </>
  )
}
